```         
```

---
title: "Predicción del gasto de luz en verano"
author: "Alejandro Andrade Guerrero"
format: html
editor: visual
---

**Instalar y cargar librerias necesarias**

```{r}
install.packages("forecast")
install.packages("tseries")
install.packages("ggplot2")
install.packages("readr")
install.packages("dplyr")
install.packages("readxl")
```

```{r}
install.packages("tseries")
library(tseries)
```

```{r}
library(forecast)
library(tseries)
library(ggplot2)
library(readr)
library(dplyr)
library(readxl)
```

***##Importar datos***

```{r}
data <- read.csv("consumo_electricidad_mexico.csv")
```

```{r}
head(data)
```

```{r}
data <- data[, c("Fecha", "Consumo")]
```

```{r}
head(data)
```

#Convertir a serie de tiempo

```{r}
library(forecast)

ts_consumo <- ts(data$Consu, start=c(2005,1), frequency=4)
```

```{r}
plot(ts_consumo)
```

***#Gráfica***

```{r}
plot(ts_consumo,
     main="Consumo de electricidad en México",
     ylab="Consumo",
     xlab="Tiempo")
```

Diferenciación necesaria

```{r}
library(forecast)

ndiffs(ts_consumo)
```

```{r}
nsdiffs(ts_consumo)
```

##Gráficas ACF y PACF

```{r}
Acf(ts_consumo)
Pacf(ts_consumo)
```

\##**Modelo SARIMA**

```{r}
modelo <- auto.arima(ts_consumo)

summary(modelo)
```

#Diagnostico

```{r}
checkresiduals(modelo_arima)
```

#Pronostico

```{r}
pronostico <- forecast(modelo, h=4)

plot(pronostico)
```

##Comparaciones

#ARIMA

```{r}
modelo_arima <- Arima(ts_consumo, order=c(1,1,1))

summary(modelo_arima)
```
